# Generated by Django 4.0.4 on 2022-06-01 19:42

from django.db import migrations
from PIL import Image


def resize_image(apps, scheme_editor):
    Ticket = apps.get_model('critics', 'Ticket')
    for ticket in Ticket.objects.all():
        if ticket.image:
            image = Image.open(ticket.image)
            image.thumbnail((600, 600))
            image.save(ticket.image.path)


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0005_alter_review_body'),
    ]

    operations = [
        migrations.RunPython(resize_image)
    ]
