# Generated by Django 4.0.4 on 2022-06-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0006_auto_20220601_1942'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together=set(),
        ),
    ]
