# Generated by Django 4.0.4 on 2022-06-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0008_alter_userfollows_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together=set(),
        ),
    ]
